development:
  ignore_files:
    - node_modules/* 
    - .gitignore 
    - .eslintignore 
    - .prettierignore 
    - package.json
    - package-lock.json
    - yarn.lock
    - .prettierrc
    - README
    - scss
    - gulpfile.js
    - DS_Store
    - .vscode
    - sitemap
